# Generated by Django 4.1.5 on 2023-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producr_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=350)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
