# Generated by Django 4.1.5 on 2023-02-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producr_name',
            new_name='product_name',
        ),
    ]
